In [56]:
from __future__ import print_function
import torch
import numpy as np

## Tensors

In [15]:
#초기화 되지 않은 5x3 행렬
x = torch.empty(5,3)
print(x) 
print(type(x)) #<class 'torch.Tensor'>

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
<class 'torch.Tensor'>


In [14]:
#무작위로 초기화된 5x3 행렬
x = torch.rand(5,3)
print(x)

tensor([[0.3805, 0.8600, 0.4351],
        [0.0584, 0.1063, 0.4554],
        [0.1108, 0.6165, 0.9189],
        [0.1677, 0.1457, 0.2678],
        [0.3446, 0.2569, 0.3335]])


In [18]:
#dtype=long, 0으로 채워진 5x3 행렬
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [20]:
#텐서 생성하기
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [21]:
#기존 텐서 이용해 새로운 텐서 만들기
x = x.new_ones(5,3, dtype=torch.double) # new_* methods take in sizes
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [23]:
#기존 텐서 이용해 새로운 텐서 만들기 -> 새로운 값 제공하지 않는한 입력 텐서의 속성을 재사용함
x = torch.randn_like(x, dtype=torch.float) # override dtype! -> result has the same size
print(x)                                     

tensor([[ 0.1906,  0.4442,  0.7628],
        [ 0.9788, -0.4636,  0.1087],
        [ 0.6712, -0.5046,  1.7789],
        [ 3.3385, -1.1798, -0.3752],
        [-1.9142,  1.7420, -0.9551]])


In [25]:
#텐서 사이즈 구하기 -> 반환값: 튜플
print(x.size())

torch.Size([5, 3])


## Operations

In [49]:
#addtion1
y = torch.rand(5,3)
print(x)
print(y)
print(x+y)

tensor([-0.6678])
tensor([[0.1248, 0.8487, 0.8999],
        [0.7487, 0.6591, 0.5920],
        [0.3360, 0.4749, 0.7679],
        [0.4065, 0.4450, 0.6871],
        [0.2882, 0.0531, 0.2522]])
tensor([[-0.5430,  0.1809,  0.2321],
        [ 0.0809, -0.0087, -0.0757],
        [-0.3318, -0.1929,  0.1001],
        [-0.2613, -0.2228,  0.0194],
        [-0.3796, -0.6146, -0.4156]])


In [50]:
#addtion2
print(torch.add(x,y))

tensor([[-0.5430,  0.1809,  0.2321],
        [ 0.0809, -0.0087, -0.0757],
        [-0.3318, -0.1929,  0.1001],
        [-0.2613, -0.2228,  0.0194],
        [-0.3796, -0.6146, -0.4156]])


In [51]:
#addition3
#출력 텐서를 인수로 제공하기
result = torch.empty(5,3)
print(result)
torch.add(x,y, out=result)
print(result)

tensor([[0.0000e+00, 1.5846e+29, 0.0000e+00],
        [1.5846e+29, 1.2612e-44, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
tensor([[-0.5430,  0.1809,  0.2321],
        [ 0.0809, -0.0087, -0.0757],
        [-0.3318, -0.1929,  0.1001],
        [-0.2613, -0.2228,  0.0194],
        [-0.3796, -0.6146, -0.4156]])


In [52]:
#addtion4
#값 변경하기
y.add_(x)
print(y)

tensor([[-0.5430,  0.1809,  0.2321],
        [ 0.0809, -0.0087, -0.0757],
        [-0.3318, -0.1929,  0.1001],
        [-0.2613, -0.2228,  0.0194],
        [-0.3796, -0.6146, -0.4156]])


In [53]:
#numpy indexing 기능 가능
print(y[:, 1])

tensor([ 0.1809, -0.0087, -0.1929, -0.2228, -0.6146])


In [54]:
#텐서 사이즈 조정하기
x = torch.randn(4,4) # [4,4]
print(x)
print(x.size())
y = x.view(16) # [16]
print(y)
print(y.size())
z = x.view(-1, 8) # [2,8]
print(z)
print(z.size())

tensor([[-6.1188e-01,  2.4278e-01, -3.8899e-01,  5.5498e-01],
        [ 5.9755e-01,  1.5871e+00,  8.0728e-01,  1.4699e-01],
        [-2.9943e-01, -5.5403e-01,  1.4515e-03, -5.9569e-01],
        [-2.0618e-01, -6.5150e-01,  1.7253e+00,  2.1894e+00]])
torch.Size([4, 4])
tensor([-6.1188e-01,  2.4278e-01, -3.8899e-01,  5.5498e-01,  5.9755e-01,
         1.5871e+00,  8.0728e-01,  1.4699e-01, -2.9943e-01, -5.5403e-01,
         1.4515e-03, -5.9569e-01, -2.0618e-01, -6.5150e-01,  1.7253e+00,
         2.1894e+00])
torch.Size([16])
tensor([[-6.1188e-01,  2.4278e-01, -3.8899e-01,  5.5498e-01,  5.9755e-01,
          1.5871e+00,  8.0728e-01,  1.4699e-01],
        [-2.9943e-01, -5.5403e-01,  1.4515e-03, -5.9569e-01, -2.0618e-01,
         -6.5150e-01,  1.7253e+00,  2.1894e+00]])
torch.Size([2, 8])


In [55]:
#텐서 요소가 1개일때, 값 가져오기
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.6268])
-0.626834511756897


## Numpy
- Torch tensor와 NumPy array는 기본 메모리 위치를 공유하며 (Torch tensor가 CPU에 있는 경우) 하나를 변경하면 다른 쪽도 변경됨
- CharTensor를 제외한 CPU의 모든 tensor는 NumPy로의 변환을 지원함

In [67]:
#torch 텐서를 numpy array로 바꾸기
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [65]:
a.add_(1)
print(a)

tensor([2., 2., 2., 2., 2.])


In [66]:
print(b)

[2. 2. 2. 2. 2.]


In [68]:
#numpy를 torch 텐서로 바꾸기
a = np.ones(5)
print("a:", a)
b = torch.from_numpy(a)
print("b:", b)

np.add(a, 1, out=a)
print("a:", a)
print("b:", b)

a: [1. 1. 1. 1. 1.]
b: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
a: [2. 2. 2. 2. 2.]
b: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA Tensors

In [70]:
"""
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!
"""

'\n# We will use ``torch.device`` objects to move tensors in and out of GPU\nif torch.cuda.is_available():\n    device = torch.device("cuda")          # a CUDA device object\n    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU\n    x = x.to(device)                       # or just use strings ``.to("cuda")``\n    z = x + y\n    print(z)\n    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!\n'