- <b>autograd</b> package provides <b>automatic differentiation</b> for all operations on Tensors.
- It is a <b>define-by-run</b> framework
    - your backprop is defined by how your code is run
    - every single iteration can be different

In [45]:
import torch

## Tensor

In [46]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [47]:
y = x+2
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [48]:
z = y*y*3
out = z.mean() # (x+2)*(x+2)*3
print(z) 
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


In [49]:
a = torch.randn(2,2)
print(a)
a = ((a*3)/(a-1))
print(a)

tensor([[-1.4738, -1.2547],
        [ 0.8723,  0.3441]])
tensor([[  1.7873,   1.6694],
        [-20.4981,  -1.5740]])


In [50]:
print(a.requires_grad) #default: False
a.requires_grad_(True)
print(a.requires_grad)

False
True


In [51]:
b = (a*a).sum()
print(b)
print(b.grad_fn)

tensor(428.6311, grad_fn=<SumBackward0>)


## Gradients

In [52]:
out.backward()

In [53]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [54]:
x = torch.randn(3, requires_grad=True)
print(x)
y = x*2
print(y)

tensor([-0.5244, -1.7257,  0.2471], requires_grad=True)
tensor([-1.0489, -3.4514,  0.4942], grad_fn=<MulBackward0>)


In [55]:
while y.data.norm() < 1000:
    y = y*2
print(y)

tensor([ -537.0199, -1767.0938,   253.0203], grad_fn=<MulBackward0>)


In [56]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
print(v)
y.backward(v)
print(y)
print(x.grad)

tensor([1.0000e-01, 1.0000e+00, 1.0000e-04])
tensor([ -537.0199, -1767.0938,   253.0203], grad_fn=<MulBackward0>)
tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [58]:
print(x.requires_grad)
print((x**2).requires_grad)

True
True


In [59]:
with torch.no_grad():
    print((x**2).requires_grad)

False


In [64]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)

True
False


In [65]:
print(x.eq(y).all())

tensor(True)
